import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['packages/*/src/**/*.test.ts', 'packages/*/tests/**/*.test.ts'],
    exclude: [
      '**/node_modules/**',
      '**/dist/**',
      'packages/extension/src/components/**/*.test.ts',
      'packages/extension/src/popup/**/*.test.ts',
    ],
    setupFiles: ['./test-setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'lcov', 'json-summary'],
      include: ['packages/*/src/**/*.ts'],
      exclude: [
        '**/*.test.ts',
        '**/*.spec.ts',
        '**/index.ts',
        '**/*.vue',
        '**/main.ts',
        '**/background/index.ts',
        '**/content/index.ts',
        '**/provider/inject.ts',
        '**/extension/src/stores/**',
        '**/extension/src/composables/**',
        '**/extension/src/popup/**',
        '**/extension/src/tab/**',
        '**/extension/src/notification/**',
        '**/extension/src/lib/messaging.ts',
        '**/extension/src/lib/uri-parser.ts',
        '**/extension/src/router/**',
        '**/extension/src/placeholder.ts',
        '**/extension/src/background/alarm-manager.ts',
        '**/extension/src/background/message-handler.ts',
        '**/extension/src/background/controllers/provider.ts',
        '**/core/src/auth/auth-passkey.ts',
        '**/core/src/auth/auth-password.ts',
        '**/core/src/network/client.ts',
        '**/core/src/storage/vault.ts',
        '**/core/src/storage/chrome-cache-storage.ts',
        '**/types/src/**',
      ],
      thresholds: {
        statements: 80,
        branches: 75,
        functions: 79,
        lines: 80,
      },
    },
  },
})
