export const ErrorCodes = {
  VAULT_NOT_FOUND: 'VAULT_NOT_FOUND',
  VAULT_ALREADY_EXISTS: 'VAULT_ALREADY_EXISTS',
  VAULT_LOCKED: 'VAULT_LOCKED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_MNEMONIC: 'INVALID_MNEMONIC',
  ACCOUNT_NOT_ACTIVATED: 'ACCOUNT_NOT_ACTIVATED',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  NETWORK_ERROR: 'NETWORK_ERROR',
  SIGNING_ERROR: 'SIGNING_ERROR',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  USER_REJECTED: 'USER_REJECTED',
  AUTO_LOCKED: 'AUTO_LOCKED',
  PASSKEY_NOT_SUPPORTED: 'PASSKEY_NOT_SUPPORTED',
  PASSKEY_REGISTRATION_FAILED: 'PASSKEY_REGISTRATION_FAILED',
  IMPORT_FORMAT_UNSUPPORTED: 'IMPORT_FORMAT_UNSUPPORTED',
  INVALID_SECRET_KEY: 'INVALID_SECRET_KEY',
  INVALID_FAMILY_SEED: 'INVALID_FAMILY_SEED',
  INVALID_PRIVATE_KEY_HEX: 'INVALID_PRIVATE_KEY_HEX',
  INVALID_XUMM_NUMBERS: 'INVALID_XUMM_NUMBERS',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  TRUSTLINE_ERROR: 'TRUSTLINE_ERROR',
  TOKEN_METADATA_ERROR: 'TOKEN_METADATA_ERROR',
  CACHE_ERROR: 'CACHE_ERROR',
  SIMULATION_FAILED: 'SIMULATION_FAILED',
  BLIND_SIGNING_DISABLED: 'BLIND_SIGNING_DISABLED',
  DAPP_NOT_CONNECTED: 'DAPP_NOT_CONNECTED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SIGNING_TIMEOUT: 'SIGNING_TIMEOUT',
  SIGNING_REJECTED: 'SIGNING_REJECTED',
  INVALID_PROVIDER_REQUEST: 'INVALID_PROVIDER_REQUEST',
  NFT_MINT_FAILED: 'NFT_MINT_FAILED',
  NFT_BURN_FAILED: 'NFT_BURN_FAILED',
  NFT_OFFER_FAILED: 'NFT_OFFER_FAILED',
  DEX_OFFER_FAILED: 'DEX_OFFER_FAILED',
  ESCROW_FAILED: 'ESCROW_FAILED',
  CHECK_FAILED: 'CHECK_FAILED',
  INSUFFICIENT_OWNER_RESERVE: 'INSUFFICIENT_OWNER_RESERVE',
  RATE_LIMITED: 'RATE_LIMITED',
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
  CONTRACT_CALL_FAILED: 'CONTRACT_CALL_FAILED',
  CONTRACT_NOT_SUPPORTED: 'CONTRACT_NOT_SUPPORTED',
  CONTRACT_INVALID_PARAMETERS: 'CONTRACT_INVALID_PARAMETERS',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

export class OtsuError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message?: string,
  ) {
    super(message ?? code)
    this.name = 'OtsuError'
  }
}
